Repository kosmos-io/clusterlink, pull requests merged in 2023-08, with the labels that each got.

#16 feat: add ci and fix some lint errors
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  cmd/clusterlink-proxy/app/clusterlink-proxy.go
  cmd/controller-manager/app/controller-manager.go
  cmd/controller-manager/app/controllerstarter.go
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/verify-codegen.sh
  hack/verify-crds.sh
  hack/verify-vendor.sh
  pkg/clusterlinkctl/floaterclient/cluster-helper.go
  pkg/clusterlinkctl/floaterclient/command/curl.go
  pkg/clusterlinkctl/floaterclient/doctor.go
  pkg/clusterlinkctl/floaterclient/floater.go
  pkg/clusterlinkctl/floaterclient/netmap/netmap.go
  pkg/clusterlinkctl/initmaster/ctlmaster/deploy_configmap.go
  pkg/clusterlinkctl/initmaster/ctlmaster/deploy_deployments.go
  pkg/clusterlinkctl/initmaster/ctlmaster/deploy_rbac.go
  pkg/clusterlinkctl/initmaster/ctlmaster/install.go
  pkg/clusterlinkctl/initmaster/ctlmaster/manifests_crd.go
  pkg/clusterlinkctl/initmaster/ctlmaster/uninstall.go
  pkg/clusterlinkctl/membercurd/options.go
  pkg/clusterlinkctl/util/apiclient/apiclient.go
  pkg/controllers/calicoippool/calicoippool_controller.go
  pkg/controllers/calicoippool/calicoippool_controller_test.go
  pkg/controllers/calicoippool/manifests.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/context/context.go
  pkg/elector/elector_test.go
  pkg/network-manager/helpers/network.go
  pkg/operator/addons/elector/elector.go
  pkg/operator/addons/global/global.go
  pkg/operator/addons/install.go
  pkg/operator/addons/manager/manager.go
  pkg/operator/addons/option/option.go
  pkg/operator/addons/proxy/proxy.go
  pkg/proxy/storage.go
  pkg/proxy/store/cluster_cache.go
  pkg/sharedcli/commandusage.go
  pkg/utils/keys/keys.go
  pkg/utils/role/role.go
  pkg/version/version.go
  test/e2e/elector_test.go
  test/e2e/suit_test.go
  vendor/modules.txt
Labels: enhancement

#20 feat: Resolve lint error
  pkg/agent/network-manager/network_manager.go
  pkg/network/iptables.go
Labels: enhancement

#21 idempotency.go skip dupl check
  pkg/operator/util/idempotency.go
Labels: invalid

#22 fix some code check prolem
  cmd/elector/app/elector.go
  pkg/agent/controller.go
  pkg/agent/network-manager/network_manager.go
  pkg/elector/elector.go
  pkg/network-manager/controller.go
  pkg/network-manager/handlers/host_network.go
  pkg/network-manager/handlers/init_nodes.go
  pkg/network-manager/handlers/nodeconfig.go
  pkg/network-manager/handlers/pod_routes.go
  pkg/network-manager/handlers/svc_routes.go
  pkg/network-manager/handlers/vxbridge_mac_cache.go
  pkg/network-manager/handlers/vxbridge_network.go
  pkg/network-manager/handlers/vxlocal_mac_cache.go
  pkg/network-manager/handlers/vxlocal_network.go
  pkg/network-manager/helpers/network.go
  pkg/network-manager/helpers/network_test.go
  pkg/network-manager/network_manager.go
  pkg/network/device.go
  pkg/network/env.go
  pkg/network/ip.go
  pkg/network/iptables.go
  pkg/network/neigh.go
  pkg/network/route.go
Labels: invalid

#24 fix: fix doctor.go lint errors
  pkg/clusterlinkctl/floaterclient/doctor.go
Labels: bug

#25 feat: linkctl support using the get command
  go.mod
  go.sum
  pkg/linkctl/get/get.go
  pkg/linkctl/linkctl.go
  vendor/github.com/fvbommel/sortorder/.gitignore
  vendor/github.com/fvbommel/sortorder/LICENSE
  vendor/github.com/fvbommel/sortorder/README.md
  vendor/github.com/fvbommel/sortorder/doc.go
  vendor/github.com/fvbommel/sortorder/natsort.go
  vendor/k8s.io/client-go/tools/watch/informerwatcher.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/client-go/tools/watch/until.go
  vendor/k8s.io/kubectl/pkg/cmd/get/customcolumn.go
  vendor/k8s.io/kubectl/pkg/cmd/get/customcolumn_flags.go
  vendor/k8s.io/kubectl/pkg/cmd/get/get.go
  vendor/k8s.io/kubectl/pkg/cmd/get/get_flags.go
  vendor/k8s.io/kubectl/pkg/cmd/get/humanreadable_flags.go
  vendor/k8s.io/kubectl/pkg/cmd/get/skip_printer.go
  vendor/k8s.io/kubectl/pkg/cmd/get/sorter.go
  vendor/k8s.io/kubectl/pkg/cmd/get/table_printer.go
  vendor/k8s.io/kubectl/pkg/rawhttp/raw.go
  vendor/k8s.io/kubectl/pkg/util/slice/slice.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
Labels: enhancement

#26 feat: globalCIDRs convert
  pkg/controllers/node/node_controller.go
  pkg/network-manager/handlers/globalmap.go
  pkg/network-manager/handlers/pod_routes.go
  pkg/network-manager/handlers/svc_routes.go
  pkg/network-manager/network_manager.go
Labels: enhancement
